### ISSUE TITLE
Form > MUI Upload > Multiple = true > Error when select file

### ISSUE THREAD

**Issue by dwitzig** [guidone/lets-form#8]
using version 0.5.6
for MUI upload component if multiple = true the following error occurs when select a file 

```
2attachment.js:1 Uncaught ReferenceError: React is not defined
    at lt (attachment.js:1:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
```

reproduced here https://codesandbox.io/p/sandbox/trusting-bird-z5w85g?file=%2Fform.js%3A20%2C9

**Comment by guidone** [comment]
Fixed in `0.5.7` (I'll fix the missing font family problem in the next release)

Thanks for the feedback
